#pragma once

#define LIBSMPP34_VERSION {{VERSION}}
#define LIBSMPP34_VERSION_STR "{{VERSION}}"

#define LIBSMPP34_VERSION_MAJOR {{VERSION_MAJOR}}
#define LIBSMPP34_VERSION_MINOR {{VERSION_MINOR}}
#define LIBSMPP34_VERSION_PATCH {{VERSION_PATCH}}

#define LIBSMPP34_VERSION_GREATER_EQUAL(major, minor, patch) \
	(LIBSMPP34_VERSION_MAJOR > (major) || \
	 (LIBSMPP34_VERSION_MAJOR == (major) && \
	  LIBSMPP34_VERSION_MINOR > (minor)) || \
	 (LIBSMPP34_VERSION_MAJOR == (major) && \
	  LIBSMPP34_VERSION_MINOR == (minor) && \
	  LIBSMPP34_VERSION_PATCH >= (patch)))
